In [13]:
import numpy as np
a=np.array([[7,2], [1,3]])
print("Matrix 1:")
print(a)
b=np.array([[9,2], [5,2]])
print("Matrix 2:")
print(b)
c=a+b
print("Matrix 3:")
print(c)

Matrix 1:
[[7 2]
 [1 3]]
Matrix 2:
[[9 2]
 [5 2]]
Matrix 3:
[[16  4]
 [ 6  5]]
